POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0Y2FhMjFmYTMxOTc2YTZiNzcwOGM5NiIsImlhdCI6MTY5MTA5MjgwNH0.io1_TCvV9xKEcj5bnNVjuyr_VvchPdP2sw4fGoG-C-4

{
  "title": "1231212",
  "author": "AddictedToPasta",
  "url" : "www.waitwhat.com",
  "likes" : "12",
  "userId": "64caa21fa31976a6b7708c96"
}
